name: Download and Upload to GitHub Pages

on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  download_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: gh-pages  # Checkout della branch gh-pages

      - name: Scarica lista file
        run: |
          wget -q -O file_list.html https://epgshare01.online/epgshare01/
          grep -oP 'href="\K[^"]+' file_list.html | grep -E "\.gz$" | grep -v "ALL_SOURCES" > files_to_download.txt

      - name: Scarica file EPG
        run: |
          while read file; do
            echo "Scaricamento $file..."
            wget -q --show-progress --limit-rate=1M "https://epgshare01.online/epgshare01/$file" -O "$file" || continue
            
            if [ -f "$file" ]; then
              filesize=$(stat -c %s "$file")
              if [ $filesize -le 100000000 ]; then
                echo "✅ $file scaricato ($filesize bytes)"
              else
                echo "⛔ $file troppo grande ($filesize bytes), eliminato"
                rm "$file"
              fi
            fi
          done < files_to_download.txt
          
          # Pulisci file vecchi (opzionale)
          find . -name "*.gz" -mtime +7 -exec rm {} \; || true

      - name: Configura Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Commit e push su gh-pages
        run: |
          git add .
          git commit -m "Aggiornamento EPG automatico $(date +'%Y-%m-%d %H:%M')" || echo "Nessun cambiamento"
          git push origin gh-pages
